name: Run Jupyter Notebook

on:
  schedule:
    # Schedule to run every day at 12:00 PM UTC
    - cron: '0 12 * * *'

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python3 -m venv env
        source env/bin/activate
        pip install jupyter pandas numpy  # Add other packages if needed

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute --inplace my_notebook.ipynb
